export const ALBUMS_LOAD = 'ALBUMS_LOAD';
export const ADD_ALBUM = 'ADD_ALBUM';
export const DELETE_ALBUM = 'DELETE_ALBUM';
export const ALL_ALBUMS_LOAD = 'ALL_ALBUMS_LOAD';
export const CURRENT_ALBUM_UPDATE = 'CURRENT_ALBUM_UPDATE';